### ISSUE TITLE
EDR processes blocklist

### ISSUE THREAD

**Issue by nclv** [netero1010/EDRSilencer#1]
Here are two lists of EDR processes you could add.

- https://github.com/nand0san/av_detect/blob/main/processes.csv
- https://github.com/FourCoreLabs/EDRHunt/tree/master/pkg/scanners

I haven't tested the tool yet, but it looks great :)

**Comment by netero1010** [comment]
Thank you for sharing the list. I have pushed a new update that includes support for additional EDRs based on the list and other references.
