### ISSUE TITLE
Blocking doesn't work

### ISSUE THREAD

**Issue by cookpoo78** [netero1010/EDRSilencer#13]
Hey,
Tried the release binary and also to compile my own (BTW, it was really challenging to compile successfully, GCC could not compile and VS required few modifications to succeed), and the WFP blocking doesn't effectively block the network traffic of the binary - I tried a number of binaries.
We can clearly see that the rule added successfully (e.g. by `netsh wfp show state`) but still the process can communicate.
![image](https://github.com/netero1010/EDRSilencer/assets/120901591/032d5c4f-d955-4b39-9803-e33087a6694e)

**Comment by netero1010** [comment]
Ping uses ICMP traffic and it is not handled by the FWPM_LAYER_ALE_AUTH_CONNECT_V4 layer in the WFP. EDRSilencer uses FWPM_LAYER_ALE_AUTH_CONNECT_V4 layer in the filter so ICMP traffic will not be restricted. You may try "C:\Windows\System32\curl.exe" for testing.

**Comment by cookpoo78** [comment]
Still experiencing this problem...
![image](https://github.com/netero1010/EDRSilencer/assets/120901591/a1bb9db7-42fa-418c-95f4-b1c0fd33db89)

**Comment by netero1010** [comment]
Hi,

Can you double check if filters are actually added in your WFP? You may check it using "WFPExp.exe". Also, could you double check if there is any WFP allow rules particularly for powreshell?

I tried to perform your case in my environment but the blocking works from my side.
![image](https://github.com/user-attachments/assets/f2417683-c821-41e1-8da9-d4d54162c5a7)
