### ISSUE TITLE
Does not work . 

### ISSUE THREAD

**Issue by ExceptionalHandler** [netero1010/EDRSilencer#18]
![image](https://github.com/user-attachments/assets/65644d43-1c0a-4747-b8ff-d7478d0377c2)

I compiled the code. 
It pushes the WFP filter 

Still could not block curl.exe

**Comment by netero1010** [comment]
![image](https://github.com/user-attachments/assets/36b7ceaf-7d6a-446f-a54e-841ccb4c6d24)
It works in my test. Can you help to double check if the WFP filter is successfully created and the binary path is correct using tools suchas WFPExp.exe, netsh.exe.

**Comment by netero1010** [comment]
From your screenshot. You are properly using Windows to compile EDRSilencer. The same issue is raised in #21 and it is fixed in the latest commit 0e73a70. Please re-test with the new code or simply try the new pre-compiled version.

Thank you!
