### ISSUE TITLE
Add EDR processes for Crowdstrike 

### ISSUE THREAD

**Issue by snolroy** [netero1010/EDRSilencer#19]
Greetings,

For testing purposes can you also please add EDR processes related to CrowdStrike ?
CSFalconService.exe           
CSFalconContainer.exe

**Comment by sec13b** [comment]
i think need you to add more : 

CSFalconContainer.exe
CSFalconService.exe"
windowssensor.x64.exe
csfalcondaterepair.exe
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Crowdstrike
    "CSFalconService.exe",
    "CSFalconContainer.exe",
    "windowssensor.x64.exe",
    "csfalcondaterepair.exe",

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
see the  in task process
but remember falcon works on kernel land

**Comment by netero1010** [comment]
Just blocking CS processes are not enough as it will leverage other Windows process (e.g., SYSTEM) to send telemetry out.

**Comment by sec13b** [comment]
how can blocking the other Windows process  to not send telemetry out.
