### ISSUE TITLE
Bug In utils.c causes Null AppID in WFP Filter

### ISSUE THREAD

**Issue by eqvsec** [netero1010/EDRSilencer#21]
utils.c contains an error that is preventing EDRSilencer from creating a WFP filter with an AppID for specifying the source process path. This causes the application to be ineffective and creates WFP filters that have no impact on connectivity.

Line 137 of utils.c:

`swprintf(ntPathBuffer, bufferSize, L"%S%S", ntDrivePath, filePath + wcslen(driveName));`

Corrected code should read:

`swprintf(ntPathBuffer, bufferSize, L"%ls%ls", ntDrivePath, filePath + wcslen(driveName));`

**Comment by netero1010** [comment]
Hi @eqvsec , thanks for correcting the code. May I know if this can solve the issue in #20 and manage to block S1 outbound connection? Unfortunately I do not have a testing instance for S1 to validate it.

**Comment by eqvsec** [comment]
> Hi @eqvsec , thanks for correcting the code. May I know if this can solve the issue in #20 and manage to block S1 outbound connection? Unfortunately I do not have a testing instance for S1 to validate it.

Yes. My testing confirmed this worked.

**Comment by netero1010** [comment]
Hi @eqvsec . Thank you! I am trying to reproduce the issue but it seems I have no problem to add a filter for "C:\Program Files\SentinelOne\Sentinel Agent 23.3.3.264\SentinelAgent.exe" with the current version of EDRSilencer. Also, from my understanding "%S" and "%ls"should do the same in this case.

Would you mind to provide more information about the issue?
- Did you compile EDRSilencer or use the pre-compiled one? and what is your compiler?
- Did you encounter this issue only for S1 case or it happens to have trouble in adding filter for other processes?

Thank you for your support!

**Comment by eqvsec** [comment]
> Hi @eqvsec . Thank you! I am trying to reproduce the issue but it seems I have no problem to add a filter for "C:\Program Files\SentinelOne\Sentinel Agent 23.3.3.264\SentinelAgent.exe" with the current version of EDRSilencer. Also, from my understanding "%S" and "%ls"should do the same in this case.
> 
> Would you mind to provide more information about the issue?
> 
>     * Did you compile EDRSilencer or use the pre-compiled one? and what is your compiler?
> 
>     * Did you encounter this issue only for S1 case or it happens to have trouble in adding filter for other processes?
> 
> 
> Thank you for your support!

I compiled with x86_64-w64-mingw32-gcc.exe EDRSilencer.c utils.c -o EDRSilencer.exe -lfwpuclnt

Interestingly, when I used the precompiled binary, the issue was not present.

Regardless of what process or EDR I ran my compiled code against, the result was the same.

![EDRSilencerFilter](https://github.com/user-attachments/assets/e86b2918-c2fa-4ffd-b761-9ae1d40bea8c)

**Comment by netero1010** [comment]
Thanks @eqvsec. I think the issue is because of this:
![image](https://github.com/user-attachments/assets/445f8950-d6ff-4f8c-a2f7-3dcfa5e94784)

Since I compile EDRSilencer in Linux so my pre-released binary does not have this issue. However, changing it to "%ls%ls" as suggested will universily fix it in both compiling platform.
![image](https://github.com/user-attachments/assets/3ed6467a-1c57-42e9-adba-759c59544736)

Thanks for bring it up and I will update it in my next commit.

**Comment by netero1010** [comment]
Just pushed the new commit 0e73a70 for this issue. Thank you very much for your help!

**Comment by eqvsec** [comment]
> Thanks @eqvsec. I think the issue is because of this:
> ![image](https://github.com/user-attachments/assets/445f8950-d6ff-4f8c-a2f7-3dcfa5e94784)
> 
> Since I compile EDRSilencer in Linux so my pre-released binary does not have this issue. However, changing it to "%ls%ls" as suggested will universily fix it in both compiling platform.
> ![image](https://github.com/user-attachments/assets/3ed6467a-1c57-42e9-adba-759c59544736)
> 
> Thanks for bring it up and I will update it in my next commit.
> 

This makes a lot of sense. Thanks for putting together this awesome project.
